import Head from "next/head";
import styles from "../styles/Upvote.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.top}>
          <div className={styles.inputcon}>
            <text className={styles.text2}>Send me an anonymous message</text>
          </div>
          <text className={styles.text3}>
            Jeffrey Afrane needs your help to update
            <br />
            this question as game in Candor
          </text>
        </div>

        <div className={styles.bottom}>
          <text className={styles.text4}>
            👇3740 people just tapped the button 👇
          </text>
          <div className={styles.button}>Upvote this poll in Candor</div>
        </div>
      </main>
    </>
  );
}
